db:
  port: 5432
  password: PONERPASSWORD
log:
  req: false
  db:
    on-demand: true
install:
  table-data-dir:
login:
  plus:
    secret: PONERSECRET
    allowHttpLogin: true
devel:
  forceShowAsEditable: false
  useFileDevelopment: true
client-setup:
  skin: ""
  lang: es
server:
  skins:
    confort:
      local-path: ../backend-skins/dist/
